import { LocationWeather } from "../models";

export const defaultHistory: LocationWeather[] = [
    {
        "location": {
            "name": "Paris",
            "region": "Ile-de-France",
            "country": "France",
            "lat": 48.8667,
            "lon": 2.3333,
            "tz_id": "Europe/Paris",
            "localtime_epoch": 1749989668,
            "localtime": "2025-06-15 14:14",
            "location_logo": "assets/icons/Flag_of_France.png"
        },
        "current": {
            "last_updated_epoch": 1749988800,
            "last_updated": "2025-06-15 14:00",
            "temp_c": 20.3,
            "temp_f": 68.5,
            "is_day": 1,
            "condition": {
                "text": "Cielo cubierto",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                "code": 1009
            },
            "wind_mph": 8.7,
            "wind_kph": 14,
            "wind_degree": 307,
            "wind_dir": "NW",
            "pressure_mb": 1024,
            "pressure_in": 30.24,
            "precip_mm": 0,
            "precip_in": 0,
            "humidity": 56,
            "cloud": 100,
            "feelslike_c": 20.3,
            "feelslike_f": 68.5,
            "windchill_c": 22.9,
            "windchill_f": 73.2,
            "heatindex_c": 24.4,
            "heatindex_f": 75.9,
            "dewpoint_c": 9.3,
            "dewpoint_f": 48.8,
            "vis_km": 10,
            "vis_miles": 6,
            "uv": 6.2,
            "gust_mph": 10,
            "gust_kph": 16.2
        },
        defaultRecord: true,
        countryCode: "FR"
    },
    {
        "location": {
            "name": "Liverpool",
            "region": "Merseyside",
            "country": "United Kingdom",
            "lat": 53.4166,
            "lon": -2.9418,
            "tz_id": "Europe/London",
            "localtime_epoch": 1749998775,
            "localtime": "2025-06-15 15:46",
            "location_logo": "assets/icons/Flag_of_England.png"
        },
        "current": {
            "last_updated_epoch": 1749998700,
            "last_updated": "2025-06-15 15:45",
            "temp_c": 17.2,
            "temp_f": 63.0,
            "is_day": 1,
            "condition": {
                "text": "Parcialmente nublado",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/116.png",
                "code": 1003
            },
            "wind_mph": 13.4,
            "wind_kph": 21.6,
            "wind_degree": 282,
            "wind_dir": "WNW",
            "pressure_mb": 1022.0,
            "pressure_in": 30.18,
            "precip_mm": 0.08,
            "precip_in": 0.0,
            "humidity": 72,
            "cloud": 75,
            "feelslike_c": 17.2,
            "feelslike_f": 63.0,
            "windchill_c": 16.2,
            "windchill_f": 61.1,
            "heatindex_c": 16.2,
            "heatindex_f": 61.1,
            "dewpoint_c": 12.3,
            "dewpoint_f": 54.1,
            "vis_km": 10.0,
            "vis_miles": 6.0,
            "uv": 2.6,
            "gust_mph": 15.4,
            "gust_kph": 24.8
        },
        defaultRecord: true,
        countryCode: "GB"
    },
    {
        "location": {
            "name": "Mexico City",
            "region": "The Federal District",
            "country": "Mexico",
            "lat": 19.4285,
            "lon": -99.1277,
            "tz_id": "America/Mexico_City",
            "localtime_epoch": 1750004073,
            "localtime": "2025-06-15 10:14",
            "location_logo": "assets/icons/Flag_of_Mexico.png"
        },
        "current": {
            "last_updated_epoch": 1750003200,
            "last_updated": "2025-06-15 10:00",
            "temp_c": 16.6,
            "temp_f": 61.9,
            "is_day": 1,
            "condition": {
                "text": "Cielo cubierto",
                "icon": "//cdn.weatherapi.com/weather/64x64/day/122.png",
                "code": 1009
            },
            "wind_mph": 2.2,
            "wind_kph": 3.6,
            "wind_degree": 93,
            "wind_dir": "E",
            "pressure_mb": 1019.0,
            "pressure_in": 30.08,
            "precip_mm": 0.0,
            "precip_in": 0.0,
            "humidity": 89,
            "cloud": 96,
            "feelslike_c": 16.6,
            "feelslike_f": 61.9,
            "windchill_c": 16.6,
            "windchill_f": 61.9,
            "heatindex_c": 16.6,
            "heatindex_f": 61.9,
            "dewpoint_c": 13.5,
            "dewpoint_f": 56.2,
            "vis_km": 5.0,
            "vis_miles": 3.0,
            "uv": 1.6,
            "gust_mph": 2.6,
            "gust_kph": 4.2
        },
        defaultRecord: true,
        countryCode: "MX"
    }
]